### ISSUE TITLE
fix your code nigga

### ISSUE THREAD

**Issue by SionM31** [yegor-kirovich/SchoolGame#22]
1: instance_activate_region(), instance_deactivate_region() is method for you
2: new object pause is solve for pause menu and weapon shop and other problems, you can make new layer that is drawn on top of the objects. Objects will still be drawn and updated, but the pause menu will cover them up.
3: game camera can draw objects when game is paused

**Comment by yegor-kirovich** [comment]
Че, нормально напиши. Я ничего не понял

**Comment by SionM31** [comment]
Короче 
1 есть методы  instance_activate_region(), instance_deactivate_region(), по названию только определенный промежуток активейт деактивейт короче вкусно классно хорошечно
2 сделать объект пауза и приделать к ней слой который будет прорисовывать все что он покрывает
3 можно через игровую камеру которая застряла на персонаже тоже сделать задачу чтобы она прорисовывала

**Comment by yegor-kirovich** [comment]
Заеб, ща сделаю. Ток я еще думал карту сделать через слои. Типа штук 10 карта и каждая карта на своем слое. В старте будем рандомить и показывать ток одну карту. Хз, как по другому карту сделать
